--- 
author: 
  - Ricardo Signes <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Package-Generator
no_index: 
  directory: 
    - inc
    - t
requires: 
  Scalar::Util: 0
  Test::More: 0
version: 0.102
